<script lang="ts" setup>
definePageMeta({
  layout: 'legal',
})

useHead({
  title: 'Privacy Policy | Galactic Gene',
  meta: [
    { name: 'description', content: 'Privacy policy for Galactic Gene astrology services and consultations.' },
  ],
})
</script>

<template>
  <div class="space-y-8 px-6 py-8 md:px-10 md:py-10">
    <div class="border-b border-amber-300/15 px-0 pb-8">
      <p class="text-sm uppercase tracking-[0.35em] text-amber-200/80">Privacy Policy</p>
      <h1 class="mt-4 text-4xl! font-semibold text-amber-200 md:text-6xl!">How we handle your information</h1>
      <p class="mt-4 max-w-3xl text-base leading-7 text-white/80 md:text-lg">
        At Galactic Gene, we keep privacy simple. We only use the information you willingly provide for astrology consultations and
        service delivery, and we do not sell, rent, or share your personal data for marketing purposes.
      </p>
    </div>

    <section>
      <h3 class="text-2xl font-semibold text-amber-200">1. Information we collect</h3>
      <div class="mt-4 space-y-4 text-white/80 leading-7">
        <p>
          We collect only the information that is necessary to provide our services. This may include your name, contact details,
          payment-related information handled through the payment gateway, and the birth details you share for astrology services,
          such as date of birth, time of birth, and place of birth.
        </p>
        <p>
          The astrologer uses the birth details you provide to prepare predictions and consultation notes. We do not use your data
          for automated profiling, behavioural advertising, or unrelated marketing.
        </p>
      </div>
    </section>

    <section>
      <h3 class="text-2xl font-semibold text-amber-200">2. No unnecessary tracking</h3>
      <div class="mt-4 space-y-4 text-white/80 leading-7">
        <p>
          The website does not track your activity for advertising or analytics purposes. We do not intentionally use invasive
          tracking tools to build user profiles or monitor your browsing behaviour beyond what is required to keep the website
          functioning.
        </p>
        <p>
          If any technical logs are generated by our hosting provider for security or maintenance, they are used only for basic
          website administration and troubleshooting.
        </p>
      </div>
    </section>

    <section>
      <h3 class="text-2xl font-semibold text-amber-200">3. How your information is used</h3>
      <div class="mt-4 space-y-4 text-white/80 leading-7">
        <p>We use your information only for the following purposes:</p>
        <ul class="list-disc space-y-2 pl-6">
          <li>to schedule and deliver consultations;</li>
          <li>to prepare astrology predictions based on the birth details you share;</li>
          <li>to communicate with you about bookings, payments, or support requests; and</li>
          <li>to comply with applicable legal, tax, or accounting obligations under Indian law.</li>
        </ul>
      </div>
    </section>

    <section>
      <h3 class="text-2xl font-semibold text-amber-200">4. Sharing of information</h3>
      <div class="mt-4 space-y-4 text-white/80 leading-7">
        <p>
          We do not share your personal data with third parties for their own marketing or commercial use. Birth details provided for
          astrology predictions are used only by the astrologer or the team members involved in delivering the consultation.
        </p>
        <p>
          We may share limited information only when necessary to process payments, complete a booking, comply with the law, or
          respond to a lawful request from an authority in India.
        </p>
      </div>
    </section>

    <section>
      <h3 class="text-2xl font-semibold text-amber-200">5. Data retention</h3>
      <div class="mt-4 space-y-4 text-white/80 leading-7">
        <p>
          We keep information only for as long as reasonably required to provide the service, maintain records, resolve disputes,
          and comply with legal obligations. If data is no longer needed, we will delete or anonymise it within a reasonable period.
        </p>
      </div>
    </section>

    <section>
      <h3 class="text-2xl font-semibold text-amber-200">6. Security</h3>
      <div class="mt-4 space-y-4 text-white/80 leading-7">
        <p>
          We take reasonable technical and organisational measures to protect the information you provide. However, no online system is
          completely secure, and we cannot guarantee absolute security during transmission or storage.
        </p>
      </div>
    </section>

    <section>
      <h3 class="text-2xl font-semibold text-amber-200">7. Your rights and choices</h3>
      <div class="mt-4 space-y-4 text-white/80 leading-7">
        <p>
          You may contact us to request access to, correction of, or deletion of information you have shared, subject to legal and
          record-keeping requirements.
        </p>
      </div>
    </section>

    <section>
      <h3 class="text-2xl font-semibold text-amber-200">8. Contact</h3>
      <div class="mt-4 space-y-4 text-white/80 leading-7">
        <p>
          If you have questions about this Privacy Policy, please contact us through the contact details provided on the website.
        </p>
      </div>
    </section>
  </div>
</template>